 // Blog.js
 import React from 'react'
 import Navbar from '../Navbar'
 function TermsAndDisclaimer() {
   return (
     <div>
       <Navbar />
       <h1>
         TargetIQ - Terms of Use & Disclaimer
       </h1>
       <p><h2>1. Acceptance of Terms</h2></p>
       <p>By accessing or using TargetIQ ("Service", "we", "our", "us"), you agree to be bound by these Terms of Use. If you do
not agree, you may not access or use the Service.
       </p>
       <br></br>
       <p><h2>2. Service Description</h2></p>
       <p>TargetIQ provides AI-generated analysis of paper shooting targets submitted by users for recreational, training, or
educational purposes only. The Service does not involve the sale, promotion, facilitation, or coordination of firearms or
ammunition.
       </p>
       <br></br>
       <p><h2>3. User Responsibilities</h2></p>
       <p>- You are solely responsible for the accuracy and legality of any images or data you upload.</p>
       <p>- You agree not to use the Service in connection with any unlawful activity, including the misuse of firearms.</p>
       <p>- You must be at least 18 years old or have guardian permission to use the Service.</p>
       <br></br>
       <p><h2>4. Firearms Disclaimer</h2></p>
       <p>TargetIQ is not affiliated with any firearm manufacturer, distributor, or training entity. The Service does not provide
live-fire coaching, weapons handling advice, or tactical instruction. TargetIQ:</p>
       <p>- Does not promote violence or illegal firearm use.</p>
       <p>- Does not facilitate firearm sales or modifications.</p>
       <p>- Is for lawful recreational, competitive, or instructional shooting practice only.</p>
       <p>We encourage all users to follow local, state, and federal laws regarding firearm use, safety, and transportation.</p>
       <br></br>
       <p><h2>5. AI and Analysis Limitations</h2></p>
       <p>All analysis and recommendations provided by TargetIQ are automatically generated by AI and may contain
inaccuracies. They are not a substitute for professional firearms training. Users are encouraged to verify all guidance
with certified instructors.
       </p>
       <br></br>
       <p><h2>6. Prohibited Use</h2></p>
       <p>- Upload offensive, violent, or illegal content (e.g., threats, criminal targets, propaganda).</p>
       <p>- Use TargetIQ in any way that violates the law or these Terms.</p>
       <p>- Attempt to reverse-engineer, extract models, or misuse our platform.</p>
       <br></br>
       <p><h2>7. Payment Processor Compliance</h2></p>
       <p>To ensure compliance with the terms of our payment processors (e.g., Stripe, PayPal):</p>
       <p>- The Service does not process payments for firearms, ammunition, or weapons-related equipment.</p>
       <p>- TargetIQ is categorized under "Software-as-a-Service" (SaaS) for sports analytics and training insights.</p>
       <p>- We reserve the right to refuse service or process refunds in the case of Terms violations or fraud.</p>
       <br></br>
       <p><h2>8. Data Privacy</h2></p>
       <p>We do not sell or share your data. Photos and performance metrics are only used to deliver reports and improve the
quality of the AI analysis. Please review our full Privacy Policy.</p>
<br></br>
      <p><h2>9. Limitation of Liability</h2></p>
       <p>TargetIQ is provided "as is" without warranties of any kind. We are not liable for:</p>
       <p>- Personal injury or property damage resulting from use of firearms.</p>
       <p>- Misinterpretation of analysis or performance advice.</p>
       <p>- Legal consequences from unlawful behavior by users.</p>
       <br></br>
       <p><h2>10. Changes to These Terms</h2></p>
       <p>We may update these Terms at any time. Continued use of the Service constitutes acceptance of the revised terms.</p>
       <br></br>
       <p><h2>11. Contact</h2></p>
       <p>For questions regarding these Terms or compliance concerns, please contact us at: email address pending</p>
       <br></br>
  <footer>
    <p>&copy; 2025 TargetIQ. All rights reserved.</p>
  </footer>
     </div>
   )
 }

 export default TermsAndDisclaimer;
